[config.wallpaper]
command = "swww"
arguments = ["img"]
set = true

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client --reload-css'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk/colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk/colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.kitty]
input_path  = '~/.config/matugen/templates/kitty/colors.conf'
output_path = '~/.config/kitty/current-theme.conf'

[templates.zed]
input_path = '~/.config/matugen/templates/zed/colors.json'
output_path = '~/.config/zed/themes/matugen.json'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel/colors.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.vesktop]
input_path = '~/.config/matugen/templates/vesktop/vesktop.css'
output_path = '~/.config/vesktop/themes/vesktop.css'

[templates.niri]
input_path = '~/.config/matugen/templates/niri/colors.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.wlogout]
input_path = '~/.config/matugen/templates/wlogout/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.color-scheme]
input_path = '~/.config/matugen/templates/qtct/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.prismlauncher]
input_path = '~/.config/matugen/templates/prismlauncher/Matugen.json'
output_path = '~/.local/share/PrismLauncher/themes/Matugen/theme.json'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox/colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.starship]
input_path = '~/.config/matugen/templates/starship/colors.toml'
output_path = '~/.config/starship.toml'

[templates.quickshell]
input_path = '~/.config/matugen/templates/quickshell/colors.qml'
output_path = '~/.config/quickshell/Common/Colors.qml'
